### ISSUE TITLE
A@+ vs A@

### ISSUE THREAD

**Issue by sturem** [CCurl/MachineForth#1]
The readme says both **A@+** and **A@**:
_"fetch a value from memory pointed to by the A register, place it on the top of the data stack, and increment A"_

Shouldn't A@ avoid the "increment A"?

(_Nice to see someone have a go at Machine Forth!_)

**Comment by CCurl** [comment]
Good catch! It was a copy/paste error. The code didn't actually do that :)

**Comment by sturem** [comment]
Great!
