### ISSUE TITLE
How to run mf?

### ISSUE THREAD

**Issue by wboeke** [CCurl/MachineForth#4]
In the past, I modified mf.c such that I could run mf like this:
```
./mf tst.f
```
The file tst.f:
```
2 3 * .
3 2 > .
3 3 = .
: tst 100 + . ;
10 tst
find = 
```
Maybe it would be a good idea to modify mf.c such that it could be run like this, out of the box?

**Comment by CCurl** [comment]
Let me see what I can do with it.

**Comment by CCurl** [comment]
OK, updated.

But please understand that this was born out of intellectual curiosity, and was never intended to be actually used for any real purpose.

**Comment by wboeke** [comment]
However then ... If you post it on github you will attract other curious people (like me), who will try your code.
But thanks, this version works.
